// gen_llms generates docs/llms.md — a condensed, LLM-optimised reference that
// aggregates README.md and all docs/*.md files into a single file.
//
// Run with:
//
//	go run ./scripts/gen_llms.go
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// sourceFiles defines the ordered list of files that feed into llms.md.
// README first (project overview), then docs in reading order.
var sourceFiles = []string{
	"README.md",
	"docs/concepts.md",
	"docs/checkpointing.md",
	"docs/streaming.md",
	"docs/human-in-the-loop.md",
	"docs/prebuilt-agents.md",
	"docs/sdk.md",
}

// sectionsToStrip are heading prefixes whose entire section should be
// dropped — they're pure navigation and add no technical content.
var sectionsToStrip = []string{
	"## What's next",
	"## Before you open a PR",
	"## License",
}

// preamble is written verbatim at the top of the generated file.
const preamble = `# gographgo — LLM Reference

> gographgo is a Go-native graph execution framework for building stateful, agentic workflows. It implements a Pregel superstep scheduler, typed state graphs, checkpointing, streaming, human-in-the-loop interrupts, and a prebuilt ReAct agent loop. Public API lives in ` + "`pkg/*`" + `; internal orchestration lives in ` + "`internal/*`" + `.
>
> **Module path:** ` + "`github.com/SkinnyPeteTheGiraffe/gographgo`" + `
>
> This file is auto-generated by ` + "`scripts/gen_llms.go`" + `. Regenerate with ` + "`go run ./scripts/gen_llms.go`" + `.

---

`

func main() {
	root, err := findModuleRoot()
	if err != nil {
		fatalf("could not find module root: %v\n", err)
	}

	var out strings.Builder
	out.WriteString(preamble)

	for _, rel := range sourceFiles {
		path := filepath.Join(root, rel)
		raw, err := os.ReadFile(path)
		if err != nil {
			fatalf("reading %s: %v\n", rel, err)
		}

		content := process(string(raw), rel)
		if content == "" {
			continue
		}
		out.WriteString(content)
		out.WriteString("\n---\n\n")
	}

	dest := filepath.Join(root, "docs", "llms.md")
	if err := os.WriteFile(dest, []byte(strings.TrimRight(out.String(), "\n")+"\n"), 0o644); err != nil {
		fatalf("writing %s: %v\n", dest, err)
	}
	fmt.Printf("wrote %s\n", dest)
}

// process cleans a source document for LLM consumption.
func process(src, filename string) string {
	// Strip the top-level H1 from every doc — the preamble handles the title.
	src = stripTopH1(src)

	// Drop navigation-only sections.
	for _, heading := range sectionsToStrip {
		src = stripSection(src, heading)
	}

	// Collapse runs of 3+ blank lines to at most 2.
	multiBlank := regexp.MustCompile(`\n{3,}`)
	src = multiBlank.ReplaceAllString(src, "\n\n")

	// Add a comment indicating source file.
	src = fmt.Sprintf("<!-- source: %s -->\n\n%s", filename, strings.TrimSpace(src))

	return strings.TrimSpace(src) + "\n\n"
}

// stripTopH1 removes the first H1 heading line from a document.
func stripTopH1(src string) string {
	lines := strings.SplitAfter(src, "\n")
	for i, line := range lines {
		if strings.HasPrefix(line, "# ") {
			lines = append(lines[:i], lines[i+1:]...)
			// Also remove a following blank line if present.
			if i < len(lines) && strings.TrimSpace(lines[i]) == "" {
				lines = append(lines[:i], lines[i+1:]...)
			}
			break
		}
	}
	return strings.Join(lines, "")
}

// stripSection removes everything from the given heading line to the next
// same-level (##) heading or end of file.
func stripSection(src, heading string) string {
	idx := strings.Index(src, "\n"+heading)
	if idx == -1 {
		// Try at start of file.
		if strings.HasPrefix(src, heading) {
			idx = 0
		} else {
			return src
		}
	} else {
		idx++ // move past the leading \n
	}

	// Find the start of the next ## heading after the target section.
	rest := src[idx+len(heading):]
	nextHeading := regexp.MustCompile(`\n##\s`)
	loc := nextHeading.FindStringIndex(rest)
	if loc == nil {
		// Section runs to end of file.
		return strings.TrimRight(src[:idx], "\n") + "\n"
	}
	return src[:idx] + rest[loc[0]:]
}

// findModuleRoot walks up from the working directory until it finds a go.mod.
func findModuleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found")
		}
		dir = parent
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format, args...)
	os.Exit(1)
}
